### PR TITLE
Podspec

### PR DESCRIPTION
**Pull request by ReDetection**
Hey look, I've made some early support for CocoaPods (it's a library dependency manager).
And also some non-damage corrections.

### CODE REVIEW

**Comment by chris-huxtable** [comment]
I appreciate your correction to the peek operation, and the creation of the pod spec. CocoaPods is something I have never used. I have to read up on the spec.

Does the ARC modification allow for it to work in an ARC and a MRC runtime? I have done little if any ARC coding so I don't know what is necessary. I also don't want to Include anything I don't fully understand. My early work with ARC in this project showed a dramatic performance decrease. I demonstrated and discovered the problem on [stackoverflow](http://stackoverflow.com/questions/22026395/how-does-nsmutablearray-achieve-such-high-speed-in-fast-enumeration).

**Comment by ReDetection** [comment]
Many thanx for quick reply!
Yes, `__unsafe_unretained` is fully safe in MRC — it will be defined as empty in this case. The cause why I added this — even if .m files compiled with `-fno-objc-arc`, header files will be included in the end programmer's code, which can be under ARC. ARC forbids passing object array without hinting who will own these objects, so compilation will fail. `__unsafe_unretained` is a mark which saying ["Trust me, I'm an engineer"](https://www.google.ru/search?q=trust+me+i'm+an+engineer) so I trust your code will do the memory work if needed. Actually, I'm sure it will, I've checked :wink: 
Yes, I understand and highly encourage your care about performance — it's very critical in the middleware and in the data structures development especially. 
You're making it right

**Comment by chris-huxtable** [comment]
I am interested in merging your podspec into the master branch, I don't know how to as there are now conflicts with the substantial modifications I have made.

Any advice?

**Comment by ReDetection** [comment]
no no no
You'd better have done it before the changes you've made. 
Actually, you've done so many things wrong so you kind of broke my heart so I'm not sure my sense of dignity permits me to help you with this. You even did force push to master branch, changing the history in a year before pull request! 
I can forgive you if you rebase your master branch onto my master branch.

**Comment by chris-huxtable** [comment]
I am assuming the 'force push' was the magic I had to do to correct a bunch of authorship issues? What would rebasing involve, what would the outcome be? I have never used git for collaborative endeavours before so other then committing I know very little. I am assuming the 'wrong' also relates to git?

**Comment by ReDetection** [comment]
According to my local cloned repo (I have both versions), you had no authorship issues before pr. 
Rebase would eliminate identical commits before pr, like these ones
screen shot 2015-05-23 at 10 33 22
and replay your commits since May 03 onto my commits, like that 
rebase hint
I would recommend you to use [SourceTree](https://www.sourcetreeapp.com) app, it is a handy graphical  wrapper to the Git.

**Pull request closed without merging**
